version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - rtd

# Don't build any extra formats
formats: []
